# Generated by Django 4.2.4 on 2023-08-31 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntaiWeb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='ProcessLink',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductLink',
        ),
        migrations.DeleteModel(
            name='RunningTables',
        ),
        migrations.DeleteModel(
            name='Shiptable',
        ),
        migrations.DeleteModel(
            name='SystemSet',
        ),
        migrations.DeleteModel(
            name='Titles',
        ),
        migrations.DeleteModel(
            name='Types',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
