# Generated by Django 4.2.4 on 2023-08-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IntaiWeb', '0002_delete_part_delete_process_delete_processlink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('PartID', models.CharField(default='', max_length=32, primary_key=True, serialize=False)),
                ('CName', models.CharField(max_length=64)),
                ('Specification', models.CharField(max_length=128)),
                ('Stock', models.IntegerField(default=0)),
                ('TypeID', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('ProcessID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('CName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessLink',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ProcessID', models.CharField(max_length=32)),
                ('ProductID', models.CharField(max_length=32)),
                ('PartID', models.CharField(max_length=32)),
                ('theOrder', models.IntegerField(default=0)),
                ('DayTarget', models.IntegerField(default=0)),
                ('Stock', models.IntegerField(default=0)),
                ('Schedule', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('CName', models.CharField(max_length=64)),
                ('FirstPass', models.FloatField(default=0)),
                ('Stock', models.IntegerField(default=0)),
                ('TypeID', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ProductID', models.CharField(max_length=32)),
                ('PartID', models.CharField(max_length=32)),
                ('PartCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RunningTables',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('TypeID', models.CharField(default='', max_length=32)),
                ('ProductID', models.CharField(default='', max_length=32)),
                ('ProcessIndex', models.IntegerField(default=0)),
                ('ProcessID', models.CharField(default='', max_length=32)),
                ('WipCount', models.FloatField(default=0)),
                ('TargetCount', models.FloatField(default=0)),
                ('SumCount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shiptable',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ProductID', models.CharField(max_length=32)),
                ('ShipDate', models.CharField(max_length=16)),
                ('TypeID', models.CharField(max_length=32)),
                ('TargetCount', models.FloatField(default=0)),
                ('WipCount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSet',
            fields=[
                ('DataName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('IntData', models.IntegerField(default=0)),
                ('DblData', models.FloatField(default=0)),
                ('StrData', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ProductID', models.CharField(max_length=32)),
                ('TypeID', models.CharField(max_length=32)),
                ('Members', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('TypeID', models.CharField(default='', max_length=32, primary_key=True, serialize=False, verbose_name='型號')),
                ('TypeName', models.CharField(max_length=64, verbose_name='名稱')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
